spring:
  application:
    name: demo-spring-boot-2-security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://st.auth.itc.gov.mn/auth/realms/demo
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

demo:
  keycloak:
    client-id: demo-spring-boot-2-security
    principle: preferred_username

server:
  port: 8083
