spring:
  application:
    name: demo-spring-boot-2-web
  datasource:
    url: jdbc:h2:mem:demoDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  batch:
    jdbc:
      initialize-schema: always
  graphql:
    graphiql:
      enabled: true

server:
  port: 8082
  error:
    include-message: always